# encoding: utf-8
Pais.create([{:nombre =>"Afganistán", :iso_codigo => 4 , :iso_alfa3 =>"AFG", :iso_alfa2 =>"AF"},
  {:nombre =>"Åland", :iso_codigo => 248 , :iso_alfa3 =>"ALA", :iso_alfa2 =>"AX"},
  {:nombre =>"Albania", :iso_codigo => 8 , :iso_alfa3 =>"ALB", :iso_alfa2 =>"AL"},
  {:nombre =>"Alemania", :iso_codigo => 276 , :iso_alfa3 =>"DEU", :iso_alfa2 =>"DE"},
  {:nombre =>"Andorra", :iso_codigo => 20 , :iso_alfa3 =>"AND", :iso_alfa2 =>"AD"},
  {:nombre =>"Angola", :iso_codigo => 24 , :iso_alfa3 =>"AGO", :iso_alfa2 =>"AO"},
  {:nombre =>"Anguila", :iso_codigo => 660 , :iso_alfa3 =>"AIA", :iso_alfa2 =>"AI"},
  {:nombre =>"Antigua y Barbuda", :iso_codigo => 28 , :iso_alfa3 =>"ATG", :iso_alfa2 =>"AG"},
  {:nombre =>"Antillas Neerlandesas", :iso_codigo => 530 , :iso_alfa3 =>"ANT", :iso_alfa2 =>"AN"},
  {:nombre =>"Arabia Saudita", :iso_codigo => 682 , :iso_alfa3 =>"SAU", :iso_alfa2 =>"SA"},
  {:nombre =>"Argelia", :iso_codigo => 12 , :iso_alfa3 =>"DZA", :iso_alfa2 =>"DZ"},
  {:nombre =>"Argentina", :iso_codigo => 32 , :iso_alfa3 =>"ARG", :iso_alfa2 =>"AR"},
  {:nombre =>"Armenia", :iso_codigo => 51 , :iso_alfa3 =>"ARM", :iso_alfa2 =>"AM"},
  {:nombre =>"Aruba", :iso_codigo => 533 , :iso_alfa3 =>"ABW", :iso_alfa2 =>"AW"},
  {:nombre =>"Australia", :iso_codigo => 36 , :iso_alfa3 =>"AUS", :iso_alfa2 =>"AU"},
  {:nombre =>"Austria", :iso_codigo => 40 , :iso_alfa3 =>"AUT", :iso_alfa2 =>"AT"},
  {:nombre =>"Azerbaiyán", :iso_codigo => 31 , :iso_alfa3 =>"AZE", :iso_alfa2 =>"AZ"},
  {:nombre =>"Bahamas", :iso_codigo => 44 , :iso_alfa3 =>"BHS", :iso_alfa2 =>"BS"},
  {:nombre =>"Baréin", :iso_codigo => 48 , :iso_alfa3 =>"BHR", :iso_alfa2 =>"BH"},
  {:nombre =>"Bangladés", :iso_codigo => 50 , :iso_alfa3 =>"BGD", :iso_alfa2 =>"BD"},
  {:nombre =>"Barbados", :iso_codigo => 52 , :iso_alfa3 =>"BRB", :iso_alfa2 =>"BB"},
  {:nombre =>"Bélgica", :iso_codigo => 56 , :iso_alfa3 =>"BEL", :iso_alfa2 =>"BE"},
  {:nombre =>"Belice", :iso_codigo => 84 , :iso_alfa3 =>"BLZ", :iso_alfa2 =>"BZ"},
  {:nombre =>"Benín", :iso_codigo => 204 , :iso_alfa3 =>"BEN", :iso_alfa2 =>"BJ"},
  {:nombre =>"Bermudas", :iso_codigo => 60 , :iso_alfa3 =>"BMU", :iso_alfa2 =>"BM"},
  {:nombre =>"Bielorrusia", :iso_codigo => 112 , :iso_alfa3 =>"BLR", :iso_alfa2 =>"BY"},
  {:nombre =>"Birmania", :iso_codigo => 104 , :iso_alfa3 =>"MMR", :iso_alfa2 =>"MM"},
  {:nombre =>"Bolivia", :iso_codigo => 68 , :iso_alfa3 =>"BOL", :iso_alfa2 =>"BO"},
  {:nombre =>"Bosnia y Herzegovina", :iso_codigo => 70 , :iso_alfa3 =>"BIH", :iso_alfa2 =>"BA"},
  {:nombre =>"Botsuana", :iso_codigo => 72 , :iso_alfa3 =>"BWA", :iso_alfa2 =>"BW"},
  {:nombre =>"Isla Bouvet", :iso_codigo => 74 , :iso_alfa3 =>"BVT", :iso_alfa2 =>"BV"},
  {:nombre =>"Brasil", :iso_codigo => 76 , :iso_alfa3 =>"BRA", :iso_alfa2 =>"BR"},
  {:nombre =>"Brunéi", :iso_codigo => 96 , :iso_alfa3 =>"BRN", :iso_alfa2 =>"BN"},
  {:nombre =>"Bulgaria", :iso_codigo => 100 , :iso_alfa3 =>"BGR", :iso_alfa2 =>"BG"},
  {:nombre =>"Burkina Faso", :iso_codigo => 854 , :iso_alfa3 =>"BFA", :iso_alfa2 =>"BF"},
  {:nombre =>"Burundi", :iso_codigo => 108 , :iso_alfa3 =>"BDI", :iso_alfa2 =>"BI"},
  {:nombre =>"Bután", :iso_codigo => 64 , :iso_alfa3 =>"BTN", :iso_alfa2 =>"BT"},
  {:nombre =>"Cabo Verde", :iso_codigo => 132 , :iso_alfa3 =>"CPV", :iso_alfa2 =>"CV"},
  {:nombre =>"Islas Caimán", :iso_codigo => 136 , :iso_alfa3 =>"CYM", :iso_alfa2 =>"KY"},
  {:nombre =>"Camboya", :iso_codigo => 116 , :iso_alfa3 =>"KHM", :iso_alfa2 =>"KH"},
  {:nombre =>"Camerún", :iso_codigo => 120 , :iso_alfa3 =>"CMR", :iso_alfa2 =>"CM"},
  {:nombre =>"Canadá", :iso_codigo => 124 , :iso_alfa3 =>"CAN", :iso_alfa2 =>"CA"},
  {:nombre =>"República Centroafricana", :iso_codigo => 140 , :iso_alfa3 =>"CAF", :iso_alfa2 =>"CF"},
  {:nombre =>"Chad", :iso_codigo => 148 , :iso_alfa3 =>"TCD", :iso_alfa2 =>"TD"},
  {:nombre =>"República Checa", :iso_codigo => 203 , :iso_alfa3 =>"CZE", :iso_alfa2 =>"CZ"},
  {:nombre =>"Chile", :iso_codigo => 152 , :iso_alfa3 =>"CHL", :iso_alfa2 =>"CL"},
  {:nombre =>"China", :iso_codigo => 156 , :iso_alfa3 =>"CHN", :iso_alfa2 =>"CN"},
  {:nombre =>"Chipre", :iso_codigo => 196 , :iso_alfa3 =>"CYP", :iso_alfa2 =>"CY"},
  {:nombre =>"Islas Cocos", :iso_codigo => 166 , :iso_alfa3 =>"CCK", :iso_alfa2 =>"CC"},
  {:nombre =>"Colombia", :iso_codigo => 170 , :iso_alfa3 =>"COL", :iso_alfa2 =>"CO"},
  {:nombre =>"Comoras", :iso_codigo => 174 , :iso_alfa3 =>"COM", :iso_alfa2 =>"KM"},
  {:nombre =>"República del Congo", :iso_codigo => 178 , :iso_alfa3 =>"COG", :iso_alfa2 =>"CG"},
  {:nombre =>"Rep. Dem. del Congo", :iso_codigo => 180 , :iso_alfa3 =>"COD", :iso_alfa2 =>"CD"},
  {:nombre =>"Islas Cook", :iso_codigo => 184 , :iso_alfa3 =>"COK", :iso_alfa2 =>"CK"},
  {:nombre =>"Corea del Norte", :iso_codigo => 408 , :iso_alfa3 =>"PRK", :iso_alfa2 =>"KP"},
  {:nombre =>"Corea del Sur", :iso_codigo => 410 , :iso_alfa3 =>"KOR", :iso_alfa2 =>"KR"},
  {:nombre =>"Costa de Marfil", :iso_codigo => 384 , :iso_alfa3 =>"CIV", :iso_alfa2 =>"CI"},
  {:nombre =>"Costa Rica", :iso_codigo => 188 , :iso_alfa3 =>"CRI", :iso_alfa2 =>"CR"},
  {:nombre =>"Croacia", :iso_codigo => 191 , :iso_alfa3 =>"HRV", :iso_alfa2 =>"HR"},
  {:nombre =>"Cuba", :iso_codigo => 192 , :iso_alfa3 =>"CUB", :iso_alfa2 =>"CU"},
  {:nombre =>"Dinamarca", :iso_codigo => 208 , :iso_alfa3 =>"DNK", :iso_alfa2 =>"DK"},
  {:nombre =>"Dominica", :iso_codigo => 212 , :iso_alfa3 =>"DMA", :iso_alfa2 =>"DM"},
  {:nombre =>"República Dominicana", :iso_codigo => 214 , :iso_alfa3 =>"DOM", :iso_alfa2 =>"DO"},
  {:nombre =>"Ecuador", :iso_codigo => 218 , :iso_alfa3 =>"ECU", :iso_alfa2 =>"EC"},
  {:nombre =>"Egipto", :iso_codigo => 818 , :iso_alfa3 =>"EGY", :iso_alfa2 =>"EG"},
  {:nombre =>"El Salvador", :iso_codigo => 222 , :iso_alfa3 =>"SLV", :iso_alfa2 =>"SV"},
  {:nombre =>"Emiratos Árabes Unidos", :iso_codigo => 784 , :iso_alfa3 =>"ARE", :iso_alfa2 =>"AE"},
  {:nombre =>"Eritrea", :iso_codigo => 232 , :iso_alfa3 =>"ERI", :iso_alfa2 =>"ER"},
  {:nombre =>"Eslovaquia", :iso_codigo => 703 , :iso_alfa3 =>"SVK", :iso_alfa2 =>"SK"},
  {:nombre =>"Eslovenia", :iso_codigo => 705 , :iso_alfa3 =>"SVN", :iso_alfa2 =>"SI"},
  {:nombre =>"España* **", :iso_codigo => 724 , :iso_alfa3 =>"ESP", :iso_alfa2 =>"ES"},
  {:nombre =>"Estados Unidos", :iso_codigo => 840 , :iso_alfa3 =>"USA", :iso_alfa2 =>"US"},
  {:nombre =>"Estonia", :iso_codigo => 233 , :iso_alfa3 =>"EST", :iso_alfa2 =>"EE"},
  {:nombre =>"Etiopía", :iso_codigo => 231 , :iso_alfa3 =>"ETH", :iso_alfa2 =>"ET"},
  {:nombre =>"Islas Feroe", :iso_codigo => 234 , :iso_alfa3 =>"FRO", :iso_alfa2 =>"FO"},
  {:nombre =>"Filipinas", :iso_codigo => 608 , :iso_alfa3 =>"PHL", :iso_alfa2 =>"PH"},
  {:nombre =>"Finlandia", :iso_codigo => 246 , :iso_alfa3 =>"FIN", :iso_alfa2 =>"FI"},
  {:nombre =>"Fiyi", :iso_codigo => 242 , :iso_alfa3 =>"FJI", :iso_alfa2 =>"FJ"},
  {:nombre =>"Francia", :iso_codigo => 250 , :iso_alfa3 =>"FRA", :iso_alfa2 =>"FR"},
  {:nombre =>"Gabón", :iso_codigo => 266 , :iso_alfa3 =>"GAB", :iso_alfa2 =>"GA"},
  {:nombre =>"Gambia", :iso_codigo => 270 , :iso_alfa3 =>"GMB", :iso_alfa2 =>"GM"},
  {:nombre =>"Georgia", :iso_codigo => 268 , :iso_alfa3 =>"GEO", :iso_alfa2 =>"GE"},
  {:nombre =>"Islas Georgias del Sur y Sandwich del Sur", :iso_codigo => 239 , :iso_alfa3 =>"SGS", :iso_alfa2 =>"GS"},
  {:nombre =>"Ghana", :iso_codigo => 288 , :iso_alfa3 =>"GHA", :iso_alfa2 =>"GH"},
  {:nombre =>"Gibraltar", :iso_codigo => 292 , :iso_alfa3 =>"GIB", :iso_alfa2 =>"GI"},
  {:nombre =>"Granada", :iso_codigo => 308 , :iso_alfa3 =>"GRD", :iso_alfa2 =>"GD"},
  {:nombre =>"Grecia", :iso_codigo => 300 , :iso_alfa3 =>"GRC", :iso_alfa2 =>"GR"},
  {:nombre =>"Groenlandia", :iso_codigo => 304 , :iso_alfa3 =>"GRL", :iso_alfa2 =>"GL"},
  {:nombre =>"Guadalupe", :iso_codigo => 312 , :iso_alfa3 =>"GLP", :iso_alfa2 =>"GP"},
  {:nombre =>"Guam", :iso_codigo => 316 , :iso_alfa3 =>"GUM", :iso_alfa2 =>"GU"},
  {:nombre =>"Guatemala", :iso_codigo => 320 , :iso_alfa3 =>"GTM", :iso_alfa2 =>"GT"},
  {:nombre =>"Guayana Francesa", :iso_codigo => 254 , :iso_alfa3 =>"GUF", :iso_alfa2 =>"GF"},
  {:nombre =>"Guernsey", :iso_codigo => 831 , :iso_alfa3 =>"GGY", :iso_alfa2 =>"GG"},
  {:nombre =>"Guinea", :iso_codigo => 324 , :iso_alfa3 =>"GIN", :iso_alfa2 =>"GN"},
  {:nombre =>"Guinea Ecuatorial", :iso_codigo => 226 , :iso_alfa3 =>"GNQ", :iso_alfa2 =>"GQ"},
  {:nombre =>"Guinea-Bisáu", :iso_codigo => 624 , :iso_alfa3 =>"GNB", :iso_alfa2 =>"GW"},
  {:nombre =>"Guyana", :iso_codigo => 328 , :iso_alfa3 =>"GUY", :iso_alfa2 =>"GY"},
  {:nombre =>"Haití", :iso_codigo => 332 , :iso_alfa3 =>"HTI", :iso_alfa2 =>"HT"},
  {:nombre =>"Islas Heard y McDonald", :iso_codigo => 334 , :iso_alfa3 =>"HMD", :iso_alfa2 =>"HM"},
  {:nombre =>"Honduras", :iso_codigo => 340 , :iso_alfa3 =>"HND", :iso_alfa2 =>"HN"},
  {:nombre =>"Hong Kong", :iso_codigo => 344 , :iso_alfa3 =>"HKG", :iso_alfa2 =>"HK"},
  {:nombre =>"Hungría", :iso_codigo => 348 , :iso_alfa3 =>"HUN", :iso_alfa2 =>"HU"},
  {:nombre =>"India", :iso_codigo => 356 , :iso_alfa3 =>"IND", :iso_alfa2 =>"IN"},
  {:nombre =>"Indonesia", :iso_codigo => 360 , :iso_alfa3 =>"IDN", :iso_alfa2 =>"ID"},
  {:nombre =>"Irán", :iso_codigo => 364 , :iso_alfa3 =>"IRN", :iso_alfa2 =>"IR"},
  {:nombre =>"Irak", :iso_codigo => 368 , :iso_alfa3 =>"IRQ", :iso_alfa2 =>"IQ"},
  {:nombre =>"Irlanda", :iso_codigo => 372 , :iso_alfa3 =>"IRL", :iso_alfa2 =>"IE"},
  {:nombre =>"Islandia", :iso_codigo => 352 , :iso_alfa3 =>"ISL", :iso_alfa2 =>"IS"},
  {:nombre =>"Israel", :iso_codigo => 376 , :iso_alfa3 =>"ISR", :iso_alfa2 =>"IL"},
  {:nombre =>"Italia", :iso_codigo => 380 , :iso_alfa3 =>"ITA", :iso_alfa2 =>"IT"},
  {:nombre =>"Jamaica", :iso_codigo => 388 , :iso_alfa3 =>"JAM", :iso_alfa2 =>"JM"},
  {:nombre =>"Japón", :iso_codigo => 392 , :iso_alfa3 =>"JPN", :iso_alfa2 =>"JP"},
  {:nombre =>"Jersey", :iso_codigo => 832 , :iso_alfa3 =>"JEY", :iso_alfa2 =>"JE"},
  {:nombre =>"Jordania", :iso_codigo => 400 , :iso_alfa3 =>"JOR", :iso_alfa2 =>"JO"},
  {:nombre =>"Kazajistán", :iso_codigo => 398 , :iso_alfa3 =>"KAZ", :iso_alfa2 =>"KZ"},
  {:nombre =>"Kenia", :iso_codigo => 404 , :iso_alfa3 =>"KEN", :iso_alfa2 =>"KE"},
  {:nombre =>"Kirguistán", :iso_codigo => 417 , :iso_alfa3 =>"KGZ", :iso_alfa2 =>"KG"},
  {:nombre =>"Kiribati", :iso_codigo => 296 , :iso_alfa3 =>"KIR", :iso_alfa2 =>"KI"},
  {:nombre =>"Kuwait", :iso_codigo => 414 , :iso_alfa3 =>"KWT", :iso_alfa2 =>"KW"},
  {:nombre =>"Laos", :iso_codigo => 418 , :iso_alfa3 =>"LAO", :iso_alfa2 =>"LA"},
  {:nombre =>"Lesoto", :iso_codigo => 426 , :iso_alfa3 =>"LSO", :iso_alfa2 =>"LS"},
  {:nombre =>"Letonia", :iso_codigo => 428 , :iso_alfa3 =>"LVA", :iso_alfa2 =>"LV"},
  {:nombre =>"Líbano", :iso_codigo => 422 , :iso_alfa3 =>"LBN", :iso_alfa2 =>"LB"},
  {:nombre =>"Liberia", :iso_codigo => 430 , :iso_alfa3 =>"LBR", :iso_alfa2 =>"LR"},
  {:nombre =>"Libia", :iso_codigo => 434 , :iso_alfa3 =>"LBY", :iso_alfa2 =>"LY"},
  {:nombre =>"Liechtenstein", :iso_codigo => 438 , :iso_alfa3 =>"LIE", :iso_alfa2 =>"LI"},
  {:nombre =>"Lituania", :iso_codigo => 440 , :iso_alfa3 =>"LTU", :iso_alfa2 =>"LT"},
  {:nombre =>"Luxemburgo", :iso_codigo => 442 , :iso_alfa3 =>"LUX", :iso_alfa2 =>"LU"},
  {:nombre =>"Macao", :iso_codigo => 446 , :iso_alfa3 =>"MAC", :iso_alfa2 =>"MO"},
  {:nombre =>"República de Macedonia", :iso_codigo => 807 , :iso_alfa3 =>"MKD", :iso_alfa2 =>"MK"},
  {:nombre =>"Madagascar", :iso_codigo => 450 , :iso_alfa3 =>"MDG", :iso_alfa2 =>"MG"},
  {:nombre =>"Malasia", :iso_codigo => 458 , :iso_alfa3 =>"MYS", :iso_alfa2 =>"MY"},
  {:nombre =>"Malaui", :iso_codigo => 454 , :iso_alfa3 =>"MWI", :iso_alfa2 =>"MW"},
  {:nombre =>"Maldivas", :iso_codigo => 462 , :iso_alfa3 =>"MDV", :iso_alfa2 =>"MV"},
  {:nombre =>"Malí", :iso_codigo => 466 , :iso_alfa3 =>"MLI", :iso_alfa2 =>"ML"},
  {:nombre =>"Malta", :iso_codigo => 470 , :iso_alfa3 =>"MLT", :iso_alfa2 =>"MT"},
  {:nombre =>"Islas Malvinas", :iso_codigo => 238 , :iso_alfa3 =>"FLK", :iso_alfa2 =>"FK"},
  {:nombre =>"Isla de Man", :iso_codigo => 833 , :iso_alfa3 =>"IMN", :iso_alfa2 =>"IM"},
  {:nombre =>"Islas Marianas del Norte", :iso_codigo => 580 , :iso_alfa3 =>"MNP", :iso_alfa2 =>"MP"},
  {:nombre =>"Marruecos", :iso_codigo => 504 , :iso_alfa3 =>"MAR", :iso_alfa2 =>"MA"},
  {:nombre =>"Islas Marshall", :iso_codigo => 584 , :iso_alfa3 =>"MHL", :iso_alfa2 =>"MH"},
  {:nombre =>"Martinica", :iso_codigo => 474 , :iso_alfa3 =>"MTQ", :iso_alfa2 =>"MQ"},
  {:nombre =>"Mauricio", :iso_codigo => 480 , :iso_alfa3 =>"MUS", :iso_alfa2 =>"MU"},
  {:nombre =>"Mauritania", :iso_codigo => 478 , :iso_alfa3 =>"MRT", :iso_alfa2 =>"MR"},
  {:nombre =>"Mayotte", :iso_codigo => 175 , :iso_alfa3 =>"MYT", :iso_alfa2 =>"YT"},
  {:nombre =>"México", :iso_codigo => 484 , :iso_alfa3 =>"MEX", :iso_alfa2 =>"MX"},
  {:nombre =>"Micronesia", :iso_codigo => 583 , :iso_alfa3 =>"FSM", :iso_alfa2 =>"FM"},
  {:nombre =>"Moldavia", :iso_codigo => 498 , :iso_alfa3 =>"MDA", :iso_alfa2 =>"MD"},
  {:nombre =>"Mónaco", :iso_codigo => 492 , :iso_alfa3 =>"MCO", :iso_alfa2 =>"MC"},
  {:nombre =>"Mongolia", :iso_codigo => 496 , :iso_alfa3 =>"MNG", :iso_alfa2 =>"MN"},
  {:nombre =>"Montenegro", :iso_codigo => 499 , :iso_alfa3 =>"MNE", :iso_alfa2 =>"ME"},
  {:nombre =>"Montserrat", :iso_codigo => 500 , :iso_alfa3 =>"MSR", :iso_alfa2 =>"MS"},
  {:nombre =>"Mozambique", :iso_codigo => 508 , :iso_alfa3 =>"MOZ", :iso_alfa2 =>"MZ"},
  {:nombre =>"Namibia", :iso_codigo => 516 , :iso_alfa3 =>"NAM", :iso_alfa2 =>"NA"},
  {:nombre =>"Nauru", :iso_codigo => 520 , :iso_alfa3 =>"NRU", :iso_alfa2 =>"NR"},
  {:nombre =>"Isla de Navidad", :iso_codigo => 162 , :iso_alfa3 =>"CXR", :iso_alfa2 =>"CX"},
  {:nombre =>"Nepal", :iso_codigo => 524 , :iso_alfa3 =>"NPL", :iso_alfa2 =>"NP"},
  {:nombre =>"Nicaragua", :iso_codigo => 558 , :iso_alfa3 =>"NIC", :iso_alfa2 =>"NI"},
  {:nombre =>"Níger", :iso_codigo => 562 , :iso_alfa3 =>"NER", :iso_alfa2 =>"NE"},
  {:nombre =>"Nigeria", :iso_codigo => 566 , :iso_alfa3 =>"NGA", :iso_alfa2 =>"NG"},
  {:nombre =>"Niue", :iso_codigo => 570 , :iso_alfa3 =>"NIU", :iso_alfa2 =>"NU"},
  {:nombre =>"Norfolk", :iso_codigo => 574 , :iso_alfa3 =>"NFK", :iso_alfa2 =>"NF"},
  {:nombre =>"Noruega", :iso_codigo => 578 , :iso_alfa3 =>"NOR", :iso_alfa2 =>"NO"},
  {:nombre =>"Nueva Caledonia", :iso_codigo => 540 , :iso_alfa3 =>"NCL", :iso_alfa2 =>"NC"},
  {:nombre =>"Nueva Zelanda", :iso_codigo => 554 , :iso_alfa3 =>"NZL", :iso_alfa2 =>"NZ"},
  {:nombre =>"Omán", :iso_codigo => 512 , :iso_alfa3 =>"OMN", :iso_alfa2 =>"OM"},
  {:nombre =>"Países Bajos", :iso_codigo => 528 , :iso_alfa3 =>"NLD", :iso_alfa2 =>"NL"},
  {:nombre =>"Pakistán", :iso_codigo => 586 , :iso_alfa3 =>"PAK", :iso_alfa2 =>"PK"},
  {:nombre =>"Palaos", :iso_codigo => 585 , :iso_alfa3 =>"PLW", :iso_alfa2 =>"PW"},
  {:nombre =>"Autoridad Nacional Palestina", :iso_codigo => 275 , :iso_alfa3 =>"PSE", :iso_alfa2 =>"PS"},
  {:nombre =>"Panamá", :iso_codigo => 591 , :iso_alfa3 =>"PAN", :iso_alfa2 =>"PA"},
  {:nombre =>"Papúa Nueva Guinea", :iso_codigo => 598 , :iso_alfa3 =>"PNG", :iso_alfa2 =>"PG"},
  {:nombre =>"Paraguay", :iso_codigo => 600 , :iso_alfa3 =>"PRY", :iso_alfa2 =>"PY"},
  {:nombre =>"Perú", :iso_codigo => 604 , :iso_alfa3 =>"PER", :iso_alfa2 =>"PE"},
  {:nombre =>"Islas Pitcairn", :iso_codigo => 612 , :iso_alfa3 =>"PCN", :iso_alfa2 =>"PN"},
  {:nombre =>"Polinesia Francesa", :iso_codigo => 258 , :iso_alfa3 =>"PYF", :iso_alfa2 =>"PF"},
  {:nombre =>"Polonia", :iso_codigo => 616 , :iso_alfa3 =>"POL", :iso_alfa2 =>"PL"},
  {:nombre =>"Portugal", :iso_codigo => 620 , :iso_alfa3 =>"PRT", :iso_alfa2 =>"PT"},
  {:nombre =>"Puerto Rico", :iso_codigo => 630 , :iso_alfa3 =>"PRI", :iso_alfa2 =>"PR"},
  {:nombre =>"Catar", :iso_codigo => 634 , :iso_alfa3 =>"QAT", :iso_alfa2 =>"QA"},
  {:nombre =>"Reino Unido", :iso_codigo => 826 , :iso_alfa3 =>"GBR", :iso_alfa2 =>"GB"},
  {:nombre =>"Reunión", :iso_codigo => 638 , :iso_alfa3 =>"REU", :iso_alfa2 =>"RE"},
  {:nombre =>"Ruanda", :iso_codigo => 646 , :iso_alfa3 =>"RWA", :iso_alfa2 =>"RW"},
  {:nombre =>"Rumania", :iso_codigo => 642 , :iso_alfa3 =>"ROU", :iso_alfa2 =>"RO"},
  {:nombre =>"Rusia", :iso_codigo => 643 , :iso_alfa3 =>"RUS", :iso_alfa2 =>"RU"},
  {:nombre =>"República Árabe Saharaui Democrática", :iso_codigo => 732 , :iso_alfa3 =>"ESH", :iso_alfa2 =>"EH"},
  {:nombre =>"Islas Salomón", :iso_codigo => 90 , :iso_alfa3 =>"SLB", :iso_alfa2 =>"SB"},
  {:nombre =>"Samoa", :iso_codigo => 882 , :iso_alfa3 =>"WSM", :iso_alfa2 =>"WS"},
  {:nombre =>"Samoa Americana", :iso_codigo => 16 , :iso_alfa3 =>"ASM", :iso_alfa2 =>"AS"},
  {:nombre =>"San Bartolomé", :iso_codigo => 652 , :iso_alfa3 =>"BLM", :iso_alfa2 =>"BL"},
  {:nombre =>"San Cristóbal y Nieves", :iso_codigo => 659 , :iso_alfa3 =>"KNA", :iso_alfa2 =>"KN"},
  {:nombre =>"San Marino", :iso_codigo => 674 , :iso_alfa3 =>"SMR", :iso_alfa2 =>"SM"},
  {:nombre =>"San Martín", :iso_codigo => 663 , :iso_alfa3 =>"MAF", :iso_alfa2 =>"MF"},
  {:nombre =>"San Pedro y Miquelón", :iso_codigo => 666 , :iso_alfa3 =>"SPM", :iso_alfa2 =>"PM"},
  {:nombre =>"San Vicente y las Granadinas", :iso_codigo => 670 , :iso_alfa3 =>"VCT", :iso_alfa2 =>"VC"},
  {:nombre =>"Santa Helena, A. y T.", :iso_codigo => 654 , :iso_alfa3 =>"SHN", :iso_alfa2 =>"SH"},
  {:nombre =>"Santa Lucía", :iso_codigo => 662 , :iso_alfa3 =>"LCA", :iso_alfa2 =>"LC"},
  {:nombre =>"Santo Tomé y Príncipe", :iso_codigo => 678 , :iso_alfa3 =>"STP", :iso_alfa2 =>"ST"},
  {:nombre =>"Senegal", :iso_codigo => 686 , :iso_alfa3 =>"SEN", :iso_alfa2 =>"SN"},
  {:nombre =>"Serbia", :iso_codigo => 688 , :iso_alfa3 =>"SRB", :iso_alfa2 =>"RS"},
  {:nombre =>"Seychelles", :iso_codigo => 690 , :iso_alfa3 =>"SYC", :iso_alfa2 =>"SC"},
  {:nombre =>"Sierra Leona", :iso_codigo => 694 , :iso_alfa3 =>"SLE", :iso_alfa2 =>"SL"},
  {:nombre =>"Singapur", :iso_codigo => 702 , :iso_alfa3 =>"SGP", :iso_alfa2 =>"SG"},
  {:nombre =>"Siria", :iso_codigo => 760 , :iso_alfa3 =>"SYR", :iso_alfa2 =>"SY"},
  {:nombre =>"Somalia", :iso_codigo => 706 , :iso_alfa3 =>"SOM", :iso_alfa2 =>"SO"},
  {:nombre =>"Sri Lanka", :iso_codigo => 144 , :iso_alfa3 =>"LKA", :iso_alfa2 =>"LK"},
  {:nombre =>"Suazilandia", :iso_codigo => 748 , :iso_alfa3 =>"SWZ", :iso_alfa2 =>"SZ"},
  {:nombre =>"Sudáfrica", :iso_codigo => 710 , :iso_alfa3 =>"ZAF", :iso_alfa2 =>"ZA"},
  {:nombre =>"Sudán", :iso_codigo => 729 , :iso_alfa3 =>"SDN", :iso_alfa2 =>"SD"},
  {:nombre =>"Sudán del Sur", :iso_codigo => 728 , :iso_alfa3 =>"SSD", :iso_alfa2 =>"SS"},
  {:nombre =>"Suecia", :iso_codigo => 752 , :iso_alfa3 =>"SWE", :iso_alfa2 =>"SE"},
  {:nombre =>"Suiza", :iso_codigo => 756 , :iso_alfa3 =>"CHE", :iso_alfa2 =>"CH"},
  {:nombre =>"Surinam", :iso_codigo => 740 , :iso_alfa3 =>"SUR", :iso_alfa2 =>"SR"},
  {:nombre =>"Svalbard y Jan Mayen", :iso_codigo => 744 , :iso_alfa3 =>"SJM", :iso_alfa2 =>"SJ"},
  {:nombre =>"Tailandia", :iso_codigo => 764 , :iso_alfa3 =>"THA", :iso_alfa2 =>"TH"},
  {:nombre =>"Taiwán", :iso_codigo => 158 , :iso_alfa3 =>"TWN", :iso_alfa2 =>"TW"},
  {:nombre =>"Tanzania", :iso_codigo => 834 , :iso_alfa3 =>"TZA", :iso_alfa2 =>"TZ"},
  {:nombre =>"Tayikistán", :iso_codigo => 762 , :iso_alfa3 =>"TJK", :iso_alfa2 =>"TJ"},
  {:nombre =>"Territorio Británico del Océano Índico", :iso_codigo => 86 , :iso_alfa3 =>"IOT", :iso_alfa2 =>"IO"},
  {:nombre =>"Territorios Australes Franceses", :iso_codigo => 260 , :iso_alfa3 =>"ATF", :iso_alfa2 =>"TF"},
  {:nombre =>"Timor Oriental", :iso_codigo => 626 , :iso_alfa3 =>"TLS", :iso_alfa2 =>"TL"},
  {:nombre =>"Togo", :iso_codigo => 768 , :iso_alfa3 =>"TGO", :iso_alfa2 =>"TG"},
  {:nombre =>"Tokelau", :iso_codigo => 772 , :iso_alfa3 =>"TKL", :iso_alfa2 =>"TK"},
  {:nombre =>"Tonga", :iso_codigo => 776 , :iso_alfa3 =>"TON", :iso_alfa2 =>"TO"},
  {:nombre =>"Trinidad y Tobago", :iso_codigo => 780 , :iso_alfa3 =>"TTO", :iso_alfa2 =>"TT"},
  {:nombre =>"Túnez", :iso_codigo => 788 , :iso_alfa3 =>"TUN", :iso_alfa2 =>"TN"},
  {:nombre =>"Islas Turcas y Caicos", :iso_codigo => 796 , :iso_alfa3 =>"TCA", :iso_alfa2 =>"TC"},
  {:nombre =>"Turkmenistán", :iso_codigo => 795 , :iso_alfa3 =>"TKM", :iso_alfa2 =>"TM"},
  {:nombre =>"Turquía", :iso_codigo => 792 , :iso_alfa3 =>"TUR", :iso_alfa2 =>"TR"},
  {:nombre =>"Tuvalu", :iso_codigo => 798 , :iso_alfa3 =>"TUV", :iso_alfa2 =>"TV"},
  {:nombre =>"Ucrania", :iso_codigo => 804 , :iso_alfa3 =>"UKR", :iso_alfa2 =>"UA"},
  {:nombre =>"Uganda", :iso_codigo => 800 , :iso_alfa3 =>"UGA", :iso_alfa2 =>"UG"},
  {:nombre =>"Uruguay", :iso_codigo => 858 , :iso_alfa3 =>"URY", :iso_alfa2 =>"UY"},
  {:nombre =>"Uzbekistán", :iso_codigo => 860 , :iso_alfa3 =>"UZB", :iso_alfa2 =>"UZ"},
  {:nombre =>"Vanuatu", :iso_codigo => 548 , :iso_alfa3 =>"VUT", :iso_alfa2 =>"VU"},
  {:nombre =>"Ciudad del Vaticano", :iso_codigo => 336 , :iso_alfa3 =>"VAT", :iso_alfa2 =>"VA"},
  {:nombre =>"Venezuela", :iso_codigo => 862 , :iso_alfa3 =>"VEN", :iso_alfa2 =>"VE"},
  {:nombre =>"Vietnam", :iso_codigo => 704 , :iso_alfa3 =>"VNM", :iso_alfa2 =>"VN"},
  {:nombre =>"Islas Vírgenes Británicas", :iso_codigo => 92 , :iso_alfa3 =>"VGB", :iso_alfa2 =>"VG"},
  {:nombre =>"Islas Vírgenes de los Estados Unidos", :iso_codigo => 850 , :iso_alfa3 =>"VIR", :iso_alfa2 =>"VI"},
  {:nombre =>"Wallis y Futuna", :iso_codigo => 876 , :iso_alfa3 =>"WLF", :iso_alfa2 =>"WF"},
  {:nombre =>"Yemen", :iso_codigo => 887 , :iso_alfa3 =>"YEM", :iso_alfa2 =>"YE"},
  {:nombre =>"Yibuti", :iso_codigo => 262 , :iso_alfa3 =>"DJI", :iso_alfa2 =>"DJ"},
  {:nombre =>"Zambia", :iso_codigo => 894 , :iso_alfa3 =>"ZMB", :iso_alfa2 =>"ZM"},
  {:nombre =>"Zimbabue", :iso_codigo => 716 , :iso_alfa3 =>"ZWE", :iso_alfa2 =>"ZW"}])